/**
 * Bundle the API into one file Vercel can boot.
 *
 * Vercel runs the service as plain Node. The workspace packages resolve fine under
 * Vitest and tsx, but they import each other with `.js` specifiers that point at `.ts`
 * sources, which Node's type-stripping does not rewrite - so the raw entrypoint fails
 * to boot even though it builds. esbuild resolves those specifiers and inlines the
 * workspace sources, emitting plain JavaScript that never hits that mismatch.
 */
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const outfile = join(here, "dist", "server.mjs");

const workspaceEntrypoints = {};
for (const pkg of ["bolt11", "domain", "rails", "router", "shared"]) {
  workspaceEntrypoints[`@satsloom/${pkg}`] = join(repoRoot, "packages", pkg, "src", "index.ts");
}

await build({
  entryPoints: [join(here, "src", "server.ts")],
  outfile,
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  // npm deps stay external for the runtime; @satsloom/* resolve to their TS sources.
  external: ["fastify", "@noble/*"],
  plugins: [
    {
      name: "satsloom-workspace",
      setup(b) {
        b.onResolve({ filter: /^@satsloom\// }, (args) => {
          const entry = workspaceEntrypoints[args.path];
          if (!entry) {
            return { errors: [{ text: `unknown @satsloom workspace package: ${args.path}` }] };
          }
          return { path: entry };
        });
      },
    },
  ],
  logLevel: "info",
  banner: {
    js: [
      "// Generated by apps/api/build.mjs - do not edit. Source: apps/api/src/server.ts",
      "import { createRequire as __createRequire } from 'module';",
      "const require = __createRequire(import.meta.url);",
    ].join("\n"),
  },
});

console.log(`bundled -> ${outfile}`);
